version: '3'
services:
  vector:
    image: timberio/vector:0.24.0-alpine
    container_name: vector
    environment:
      - DD_API_KEY=xxxxxxxxxx # Update your api key
      - DD_CONFIGURATION_KEY=xxxxxxxxxx # Update your configuration key
    volumes:
      - ./vector.toml.obs-pipeline:/etc/vector/vector.toml
    ports:
      - 8080:8080/tcp
      - 8686:8686/tcp
    networks:
      - my-dd-network
networks:
   my-dd-network:
     external: true
